name: skl_tut
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip=25.1
  - pip:
    - numpy==2.4.4
    - scipy==1.17.1
    - matplotlib==3.10.9
    - scikit-learn==1.8.0
    - jupyterlab==4.5.7
    - ipywidgets==8.1.8
    - pandas==3.0.2
    - nltk==3.9.4
    - selenium==4.43.0
    - beautifulsoup4==4.14.3
    - pypdf==6.10.2
